version: '3.9'

services:
  zoo-local:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zoo-local
    container_name: zoo-local
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo-local:2888:3888

  kafka-local:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka-local
    container_name: kafka-local
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zoo-local:2181
      KAFKA_LISTENERS: LISTENER_BOB://kafka-local:29092,LISTENER_FRED://kafka-local:9092,LISTENER_ALICE://kafka-local:29094
      KAFKA_ADVERTISED_LISTENERS: LISTENER_BOB://kafka-local:29092,LISTENER_FRED://localhost:9092,LISTENER_ALICE://never-gonna-give-you-up:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_BOB:PLAINTEXT,LISTENER_FRED:PLAINTEXT,LISTENER_ALICE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_BOB
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    depends_on:
      - zoo-local

