apiVersion: v1
kind: ConfigMap
metadata:
  name: database
  namespace: teaching_ns
data:
  # property-like keys; each key maps to a simple value
  POSTGRES_DB: "teaching_de"
  POSTGRES_USER: "teaching_de"