apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: teaching_ns
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: timescale/timescaledb:latest-pg16
        ports:
        - containerPort: 5432