### GET a duck for the given duck id
GET http://localhost:8080/duck/1
Accept: text/plain

### post a new duck and get the corresponding ID back
POST http://localhost:8080/duck
Content-Type: application/json

{
"age": 18,
"address": "ducktown 35A",
"name": "Donalda",
"favorite_pond": "Kralingse plas"
}